version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/sweetshop
      - PORT=5000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sweetshop
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
